language: objective-c
osx_image: xcode8.3
before_install: pod repo update
cache: cocoapods
xcode_workspace: WFByr.xcworkspace
xcode_scheme: WFByr
script:
- xcodebuild clean build -sdk iphonesimulator -workspace WFByr.xcworkspace -scheme WFByr CODE_SIGNING_REQUIRED=NO
- xcodebuild test  -workspace WFByr.xcworkspace -scheme WFByr -destination 'platform=iOS Simulator,name=iPhone 6s,OS=10.3.1'
