language: objective-c
osx_image: xcode8.3
before_install:
    - pod repo update
    - export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone 6s (10.3.1" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
    - echo $IOS_SIMULATOR_UDID
    - open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID
cache: cocoapods
xcode_workspace: WFByr.xcworkspace
xcode_scheme: WFByr
script:
    - xcodebuild clean build -sdk iphonesimulator -workspace WFByr.xcworkspace -scheme WFByr CODE_SIGNING_REQUIRED=NO
    - xcodebuild test  -workspace WFByr.xcworkspace -scheme WFByr -destination 'platform=iOS Simulator,name=iPhone 6s,OS=10.3.1'
